// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJTAZXGQk98Ey7TLtUrtA3ot1_Xyfkhxg',
    appId: '1:997364373900:web:2ae46c2d5dfa0fc671dea9',
    messagingSenderId: '997364373900',
    projectId: 'ex-book-6fb70',
    authDomain: 'ex-book-6fb70.firebaseapp.com',
    storageBucket: 'ex-book-6fb70.appspot.com',
    measurementId: 'G-XCKKX807SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1RSSpkIT7qxrY5-f09o7b8bM0IUXwy4',
    appId: '1:997364373900:android:594d8152ce63b20a71dea9',
    messagingSenderId: '997364373900',
    projectId: 'ex-book-6fb70',
    storageBucket: 'ex-book-6fb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRs4v3C4XVqQb13R1Bz0apDKct5ksoftY',
    appId: '1:997364373900:ios:9e563aaca138cb1671dea9',
    messagingSenderId: '997364373900',
    projectId: 'ex-book-6fb70',
    storageBucket: 'ex-book-6fb70.appspot.com',
    iosClientId: '997364373900-2184725i16u3fqr2h742hf8a9k0q5j2c.apps.googleusercontent.com',
    iosBundleId: 'com.taquangkhoi.exBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRs4v3C4XVqQb13R1Bz0apDKct5ksoftY',
    appId: '1:997364373900:ios:43db831647ec82dd71dea9',
    messagingSenderId: '997364373900',
    projectId: 'ex-book-6fb70',
    storageBucket: 'ex-book-6fb70.appspot.com',
    iosClientId: '997364373900-ifdqpjv3mqn0c76itb2olkgcmeatcpha.apps.googleusercontent.com',
    iosBundleId: 'com.taquangkhoi.exBook.RunnerTests',
  );
}
